{% set version = "1.7" %}
{% set sha256 = "a5e6a0a9ab69f40f0f59332106532ca76918977a974e7004977a9498e3f11350" %}

package:
  name: libdeflate
  version: {{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libdeflate', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]

test:
  commands:
    - test ! -f ${PREFIX}/lib/libdeflate.a          # [unix]
    - test -f ${PREFIX}/lib/libdeflate${SHLIB_EXT}  # [unix]
    - libdeflate-gzip -h
    - libdeflate-gunzip -h

about:
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  license_file: COPYING
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.

extra:
  recipe-maintainers:
    - dpryan79
    - rhpvorderman
    - hmaarrfk
