travis:
  secure:
    BINSTAR_TOKEN: MW2/t8lPUwf7TdiBytM3TV7XjpBxQPopnqMwskyrlS2OjJpRX+W4tgmecQEu4o7EHC2HvmZyMOfnnE1ZxBIlLPK14q0JymQVulgKoRGKibvkhhmQz4/Gm1l3DDDqvZF03ABko80WtaU4Aj1goKlpOV3m/qmabZbwdtve2D7Do+qH1D3VxzK1tlQT3ruRMuWi8gHU5i1Iw4PTM59SZCSqgcRmtYrKOKKwoh4hzUgnEDpagLmerLxOmytos4kevzkMhJrkPv0209pV47vFzTS2fgLOGzIFA0z8ey0lz/fOCNt+NfX4N2Hlsn9JMVnVTQwnyshVGcuxX2GfnntPTNCpBHbGHtgqoKXoEXk+UhXHHTf+CmqtAub2DF4WFof4KTL5n2TUEPTIx5B8Q2JUFp2UFYUosxVdxziJIKTaIhcViFHcToE2/ZJrGjUPJ405+g0j4uBCrZB26GG8AkekJfXeDdWeApboD1nVtVaACHBoYICx93kvd8E1+vNnNSOsbm6kY9LyCinQnQ/vtYe+O38m3hgWF5t8v3egDcm2j/vRa0Iv3fAbx2OaFP9kXRPyQjms7wGAtMA1LQ1EwtgU/devmSJ7JgwyukN2QHy7nw4tJXT48y+mwxX93cDilduXJNAh7aQhdTnSMNp/5Y+J9QEJAismWspIes42ZSv1MKQuxGE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
